FROM rockylinux/rockylinux:10

RUN dnf clean all && \
    dnf makecache && \
    dnf install -y epel-release && \
    dnf makecache && \
    dnf install -y \
        git dos2unix tar gzip curl \
        python3 python3-pip \
        openssh-clients \
        "@Development Tools" \
        autoconf automake libtool \
        ncurses-devel libpcap readline-devel \
        bash net-tools \
        glibc-langpack-en glibc-langpack-zh \
        iproute iputils bind-utils \
        libstdc++ libgcc monit lsof telnet vim less procps-ng systemd && \
    dnf clean all

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN mkdir -p /root/.ssh /root/q && \
    echo "StrictHostKeyChecking no" >> /root/.ssh/config && \
    chmod 600 /root/.ssh/config

RUN echo "alias python=python3" >> /root/.bashrc && \
    echo "alias pip=pip3" >> /root/.bashrc
